/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TaitGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrew Tait (1504593) 
 * Date: 22/1/2016 
 * Description: Add Mail item dialog - Add an mail item to a van based on it's ID/Index
 */
public class AddMailItem extends javax.swing.JDialog
{

    private Fleet ft;
    private int vanID;
    private Person recipient;
    private String firstName;
    private String secondName;

    /**
     * Creates new form AddMailItem
     */
    public AddMailItem(java.awt.Frame parent, boolean modal, Fleet ft, int vanID)
      {
        super(parent, modal);
        initComponents();
        this.ft = ft;
        this.vanID = vanID;
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelSurname = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelLetter = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldMailAddress = new javax.swing.JTextField();
        jTextFieldMailPostcode = new javax.swing.JTextField();
        jComboBoxMailType = new javax.swing.JComboBox();
        jTextFieldParcelWeight = new javax.swing.JTextField();
        jRadioButtonFirstClass = new javax.swing.JRadioButton();
        jRadioButtonSecondClass = new javax.swing.JRadioButton();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();

        buttonGroup1.add(this.jRadioButtonFirstClass);
        buttonGroup1.add(this.jRadioButtonSecondClass);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Mail Item to Van");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Driver Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, 79, -1));

        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 11, 65, 35));

        jLabelFirstName.setText("FIRSTNAME");
        getContentPane().add(jLabelFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 21, 120, -1));

        jLabel4.setText("Surname:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 21, -1, -1));

        jLabelSurname.setText("SURNAME");
        getContentPane().add(jLabelSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 21, 140, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 83, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 530, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Mail Item Address");

        jLabel5.setText("Mail Item PostCode");

        jLabel6.setText("MailItem Type");

        jLabel7.setText("Parcel Weight");

        jLabelLetter.setText("Letter Class");

        jLabel8.setText("Recipient First Name");

        jLabel9.setText("Recipient Last Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLetter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 330));

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createCompoundBorder()));

        jComboBoxMailType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Express Parcel", "Parcel", "Letter" }));
        jComboBoxMailType.setToolTipText("");
        jComboBoxMailType.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxMailTypeActionPerformed(evt);
            }
        });

        jTextFieldParcelWeight.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldParcelWeightActionPerformed(evt);
            }
        });

        jRadioButtonFirstClass.setSelected(true);
        jRadioButtonFirstClass.setText("First Class");

        jRadioButtonSecondClass.setText("Second Class");
        jRadioButtonSecondClass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonSecondClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldMailPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRadioButtonFirstClass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonSecondClass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldParcelWeight, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxMailType, javax.swing.GroupLayout.Alignment.LEADING, 0, 146, Short.MAX_VALUE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldMailPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jComboBoxMailType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldParcelWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFirstClass)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonSecondClass)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 350, 330));

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jButtonSubmit.setText("OK");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jRadioButtonSecondClassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonSecondClassActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonSecondClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSecondClassActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSubmitActionPerformed
    {//GEN-HEADEREND:event_jButtonSubmitActionPerformed
        //Field variables
        String address;
        String postCode;
        String recipientFName;
        String recipientSName;
        int mailTypeIndex;
        int parcelWeight;
        boolean letterClass = false;
        boolean isValidInput = false;

        try
          {
            recipientFName = this.jTextFieldFirstName.getText();
            recipientSName = this.jTextFieldLastName.getText();

            address = this.jTextFieldMailAddress.getText();
            postCode = this.jTextFieldMailPostcode.getText();

            if ("".equals(recipientFName) || "".equals(recipientSName) || "".equals(address) || "".equals(postCode))
              {
                JOptionPane.showMessageDialog(null, "Please enter all fields!", "Warning!", JOptionPane.WARNING_MESSAGE);
              } else
              {

                recipient = new Person(recipientFName, recipientSName);
                Addressee a1 = new Addressee(this.recipient, address, postCode);

                //Check what MailItem type it is
                mailTypeIndex = this.jComboBoxMailType.getSelectedIndex();
                switch (mailTypeIndex)
                  {
                    //Express Parcel
                    case 0:
                        if (this.jTextFieldParcelWeight.getText().equals("") || this.jTextFieldParcelWeight.getText().equals("0") || Integer.parseInt(this.jTextFieldParcelWeight.getText()) < 0)
                          {
                            JOptionPane.showMessageDialog(null, "Invalid weight input!", "Warning!", JOptionPane.WARNING_MESSAGE);

                          } else
                          {
                            parcelWeight = Integer.parseInt(this.jTextFieldParcelWeight.getText());
                            System.out.println(parcelWeight);
                            ExpressParcel ep1 = new ExpressParcel(a1, parcelWeight);
                            //Add all the information together to create a MailItem
                            this.ft.getVan(this.vanID).getItems().add(ep1);
                            isValidInput = true;
                          }
                        break;
                    //Parcel    
                    case 1:
                        parcelWeight = Integer.parseInt(this.jTextFieldParcelWeight.getText());
                        Parcel p1 = new Parcel(a1, parcelWeight);
                        //Add all the information together to create a MailItem
                        this.ft.getVan(this.vanID).getItems().add(p1);
                        isValidInput = true;
                        break;

                    //Letter     
                    case 2:
                        if (this.jRadioButtonFirstClass.isSelected())
                          {
                            letterClass = true;
                          } else if (this.jRadioButtonSecondClass.isSelected())
                          {
                            letterClass = false;
                          }
                        Letter l1 = new Letter(a1, letterClass);
                        //Add all the information together to create a MailItem
                        this.ft.getVan(this.vanID).getItems().add(l1);
                        isValidInput = true;
                        break;
                  }

              }
          } catch (NumberFormatException e)
          {
            JOptionPane.showMessageDialog(null, "Invalid Input please try again", "Error!", JOptionPane.ERROR_MESSAGE);
          }

        //If all inputs are validated and processed, close dialog window
        if (isValidInput)
          {
            JOptionPane.showMessageDialog(null, "Mail Item Succesfully Added!");
            this.setVisible(false);
          }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // Once form is opened perform these actions:
        //Get driver name and set labels on form
        firstName = ft.getVan(this.vanID).getDriver().getFirstName();
        secondName = ft.getVan(this.vanID).getDriver().getSecondName();
        this.jLabelFirstName.setText(firstName);
        this.jLabelSurname.setText(secondName);

        //Get Person Object for MailItem
        //driver = ft.getVan(this.vanID).getDriver();
        //Hide fields based on combobox selection
        if (this.jComboBoxMailType.getSelectedIndex() == 0 || this.jComboBoxMailType.getSelectedIndex() == 1)
          {
            this.jRadioButtonFirstClass.setVisible(false);
            this.jRadioButtonSecondClass.setVisible(false);
            this.jLabelLetter.setVisible(false);
            this.jTextFieldParcelWeight.setEditable(true);
          } else if (this.jComboBoxMailType.getSelectedIndex() == 2)
          {
            this.jTextFieldParcelWeight.setEditable(false);
          }

    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxMailTypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxMailTypeActionPerformed
    {//GEN-HEADEREND:event_jComboBoxMailTypeActionPerformed
        if (this.jComboBoxMailType.getSelectedIndex() == 0 || this.jComboBoxMailType.getSelectedIndex() == 1)
          {
            this.jRadioButtonFirstClass.setVisible(false);
            this.jRadioButtonSecondClass.setVisible(false);
            this.jLabelLetter.setVisible(false);
            this.jTextFieldParcelWeight.setEditable(true);
          } else if (this.jComboBoxMailType.getSelectedIndex() == 2)
          {
            this.jTextFieldParcelWeight.setEditable(false);
            this.jRadioButtonFirstClass.setVisible(true);
            this.jRadioButtonSecondClass.setVisible(true);
            this.jLabelLetter.setVisible(true);
          }
    }//GEN-LAST:event_jComboBoxMailTypeActionPerformed

    private void jTextFieldParcelWeightActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldParcelWeightActionPerformed
    {//GEN-HEADEREND:event_jTextFieldParcelWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelWeightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox jComboBoxMailType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLetter;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFirstClass;
    private javax.swing.JRadioButton jRadioButtonSecondClass;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMailAddress;
    private javax.swing.JTextField jTextFieldMailPostcode;
    private javax.swing.JTextField jTextFieldParcelWeight;
    // End of variables declaration//GEN-END:variables
}
