/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TaitGUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrew Tait(1504693)
 * Date: 22/1/2015
 * Description: Edit Mail Item Dialog, based on van and Mail Item ID
 */
public class EditMailItem extends javax.swing.JDialog
{

    private Fleet ft;
    private int vanID;
    private int mailItemID;
    private String address;
    private String postCode;
    private String recipientFName;
    private String recipientSName;
    private int mailTypeIndex;
    private int parcelWeight;
    private String mailType;
    private boolean letterClass = false;
    private MailItem mailItem;
    private Person recipient;

    /**
     * Creates new form EditMailItem
     */
    public EditMailItem(java.awt.Frame parent, boolean modal, Fleet ft, int vanID, int mailItemID)
      {
        super(parent, modal);
        initComponents();
        this.ft = ft;
        this.vanID = vanID;
        this.mailItemID = mailItemID;
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonSubmit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelLetter = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldMailAddress = new javax.swing.JTextField();
        jTextFieldMailPostcode = new javax.swing.JTextField();
        jTextFieldParcelWeight = new javax.swing.JTextField();
        jRadioButtonFirstClass = new javax.swing.JRadioButton();
        jRadioButtonSecondClass = new javax.swing.JRadioButton();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelMailType = new javax.swing.JLabel();

        buttonGroup1.add(this.jRadioButtonFirstClass);
        buttonGroup1.add(this.jRadioButtonSecondClass);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Mail Item");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jButtonSubmit.setText("OK");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Mail Item Address");

        jLabel5.setText("Mail Item PostCode");

        jLabel6.setText("MailItem Type");

        jLabel7.setText("Parcel Weight (G)");

        jLabelLetter.setText("Letter Class");

        jLabel8.setText("Recipient First Name");

        jLabel9.setText("Recipient Last Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLetter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createCompoundBorder()));

        jTextFieldParcelWeight.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldParcelWeightActionPerformed(evt);
            }
        });

        jRadioButtonFirstClass.setText("First Class");

        jRadioButtonSecondClass.setText("Second Class");
        jRadioButtonSecondClass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonSecondClassActionPerformed(evt);
            }
        });

        jLabelMailType.setText("MAILTYPE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldMailPostcode)
                    .addComponent(jTextFieldMailAddress)
                    .addComponent(jTextFieldFirstName)
                    .addComponent(jTextFieldLastName)
                    .addComponent(jRadioButtonFirstClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonSecondClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldParcelWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMailType, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldMailPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMailType)
                .addGap(32, 32, 32)
                .addComponent(jTextFieldParcelWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFirstClass)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonSecondClass)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jButtonCancel))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        //Determine what type of mailItem it is.
        mailItem = this.ft.getVan(this.vanID).getItems().get(this.mailItemID);
        if (mailItem instanceof Letter)
          {
            System.out.println("It's a Letter!");
            Letter l1 = (Letter) mailItem;
            this.mailType = "Letter";
            //Person Details
            this.recipientFName = l1.getAddressee().getName().getFirstName();
            this.recipientSName = l1.getAddressee().getName().getSecondName();
            System.out.println(this.recipientFName);
            System.out.println(this.recipientSName);
            //Address Details
            this.address = l1.getAddressee().getAddress();
            this.postCode = l1.getAddressee().getPostCode();
            //Set letter class based on boolean
            if (l1.isFirstClass())
              {
                this.jRadioButtonFirstClass.setSelected(true);
              } else if (!l1.isFirstClass())
              {
                this.jRadioButtonSecondClass.setSelected(true);
              }

            this.jLabelMailType.setText(this.mailType);
            this.jTextFieldFirstName.setText(this.recipientFName);
            this.jTextFieldLastName.setText(this.recipientSName);
            this.jTextFieldMailAddress.setText(this.address);
            this.jTextFieldMailPostcode.setText(this.postCode);

//            Hide Parcel forms
            this.jTextFieldParcelWeight.setEditable(false);
            this.jRadioButtonFirstClass.setVisible(true);
            this.jRadioButtonSecondClass.setVisible(true);
            this.jLabelLetter.setVisible(true);
          } else if (mailItem instanceof Parcel)
          {
            Parcel p1 = (Parcel) mailItem;

            this.mailType = "Parcel";
            if (mailItem instanceof ExpressParcel)
              {
                this.mailType = "Express Parcel";
              }

            //Get parcel Details
            //Person Details
            this.recipientFName = p1.getAddressee().getName().getFirstName();
            this.recipientSName = p1.getAddressee().getName().getSecondName();
            //Address Details
            this.address = p1.getAddressee().getAddress();
            this.postCode = p1.getAddressee().getPostCode();
            //Parcel Weight
            this.parcelWeight = p1.getWeight();

            //Set info to form fields
            this.jLabelMailType.setText(this.mailType);
            this.jTextFieldFirstName.setText(this.recipientFName);
            this.jTextFieldLastName.setText(this.recipientSName);
            this.jTextFieldMailAddress.setText(this.address);
            this.jTextFieldMailPostcode.setText(this.postCode);
            this.jTextFieldParcelWeight.setText(Integer.toString(this.parcelWeight));

            //Hide letter forms
            this.jRadioButtonFirstClass.setVisible(false);
            this.jRadioButtonSecondClass.setVisible(false);
            this.jLabelLetter.setVisible(false);
            this.jTextFieldParcelWeight.setEditable(true);

          }


    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldParcelWeightActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldParcelWeightActionPerformed
    {//GEN-HEADEREND:event_jTextFieldParcelWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelWeightActionPerformed

    private void jRadioButtonSecondClassActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonSecondClassActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonSecondClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSecondClassActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSubmitActionPerformed
    {//GEN-HEADEREND:event_jButtonSubmitActionPerformed
        // Update mailItem

        boolean isValidInput = false;

        try
          {
            recipientFName = this.jTextFieldFirstName.getText();
            recipientSName = this.jTextFieldLastName.getText();

            address = this.jTextFieldMailAddress.getText();
            postCode = this.jTextFieldMailPostcode.getText();

            //Input Validation
            if ("".equals(recipientFName) || "".equals(recipientSName) || "".equals(address) || "".equals(postCode))
              {
                JOptionPane.showMessageDialog(null, "Please enter all fields!", "Warning!", JOptionPane.WARNING_MESSAGE);
              } else
              {
                recipient = new Person(recipientFName, recipientSName);
                Addressee updatedAddress = new Addressee(this.recipient, address, postCode);
                switch (this.mailType)
                  {
                    case "Parcel":
                        if (this.jTextFieldParcelWeight.getText().equals("") || this.jTextFieldParcelWeight.getText().equals("0"))
                          {
                            JOptionPane.showMessageDialog(null, "Invalid weight input!", "Warning!", JOptionPane.WARNING_MESSAGE);

                          } else
                          {
                            parcelWeight = Integer.parseInt(this.jTextFieldParcelWeight.getText());
                            mailItem.setAddressee(updatedAddress);
                            Parcel UpdatedParcel = (Parcel) mailItem;
                            UpdatedParcel.setWeight(parcelWeight);
                            isValidInput = true;
                          }
                        break;

                    case "Express Parcel":
                        if (this.jTextFieldParcelWeight.getText().equals("") || this.jTextFieldParcelWeight.getText().equals("0"))
                          {
                            JOptionPane.showMessageDialog(null, "Invalid weight input!", "Warning!", JOptionPane.WARNING_MESSAGE);

                          } else
                          {
                            parcelWeight = Integer.parseInt(this.jTextFieldParcelWeight.getText());
                            mailItem.setAddressee(updatedAddress);
                            ExpressParcel UpdatedEP = (ExpressParcel) mailItem;
                            UpdatedEP.setWeight(parcelWeight);
                            isValidInput = true;
                          }
                        break;
                    case "Letter":
                        if (this.jRadioButtonFirstClass.isSelected())
                          {
                            letterClass = true;
                          } else if (this.jRadioButtonSecondClass.isSelected())
                          {
                            letterClass = false;
                          }
                        mailItem.setAddressee(updatedAddress);
                        Letter UpdatedLetter = (Letter) mailItem;
                        UpdatedLetter.setFirstClass(letterClass);
                        isValidInput = true;
                        break;
                  }
              }

          } catch (NumberFormatException e)
          {
            JOptionPane.showMessageDialog(null, "Invalid Input please try again", "Error!", JOptionPane.ERROR_MESSAGE);
          }

        if (isValidInput)
          {
            JOptionPane.showMessageDialog(null, "Mail Item Succesfully Updated!");
            this.setVisible(false);
          }
    }//GEN-LAST:event_jButtonSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLetter;
    private javax.swing.JLabel jLabelMailType;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFirstClass;
    private javax.swing.JRadioButton jRadioButtonSecondClass;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMailAddress;
    private javax.swing.JTextField jTextFieldMailPostcode;
    private javax.swing.JTextField jTextFieldParcelWeight;
    // End of variables declaration//GEN-END:variables
}
